write_mod_param_help_inner <- function(elem, depth = 1) {
  docs <- attr(elem, "docs")

  indentation <- strrep("  ", times = depth)

  cardinality <- if (isTRUE(attr(elem, "zero_or_more"))) "(n)" else ""

  res <- sprintf("#' `[%s%s]`", docs[["type"]], cardinality)

  if (isTRUE(attr(elem, "optional"))) res <- paste(res, "(optional)")

  if (nchar(docs[["manual_desc"]]) > 0) {
    manual_desc <- paste0(docs[["manual_desc"]], ".")
    manual_desc <- paste("#' ", strwrap(manual_desc, width = 80))
    res <- c(res, manual_desc)
  }

  if (length(docs[["auto_desc"]])) {
    auto_desc <- paste0(docs[["auto_desc"]], ".") |> paste(collapse = " ")
    auto_desc <- paste("#' ", strwrap(auto_desc, width = 80))
    res <- c(res, auto_desc)
  }

  if (elem$kind == "group") {
    res <- c(res, "#' Composed of:")

    subelem_names <- names(elem[["elements"]])
    for (i_elem in seq_along(elem[["elements"]])) {
      subelem <- elem[["elements"]][[i_elem]]
      res <- c(
        res,
        paste(
          sprintf("#'%s*", indentation),
          subelem_names[[i_elem]]
        ),
        write_mod_param_help_inner(subelem, depth + 1)
      )
    }
  }

  return(res)
}

write_mod_param_help <- function() {
  env <- new.env()
  mod_API_path <- system.file("R/mod_API.R", package = "dv.papo", mustWork = TRUE)
  source(mod_API_path, local = env)
  api <- env[["mod_patient_profile_API"]][["elements"]]

  head <- c(
    "#' Dummy function to extract parameter documentation from mod_patient_profile_API",
    "#'",
    "#' Generated by `write_mod_param_help.R`.",
    "#'",
    "#' @keywords internal",
    "#'"
  )

  param_docs <- c()

  param_names <- names(api)
  for (i_param in seq_along(api)) {
    param_name <- param_names[[i_param]]
    param <- api[[i_param]]
    param_head <- paste("#' @param", param_name)
    param_tail <- write_mod_param_help_inner(param)
    param_docs <- c(param_docs, param_head, param_tail)
  }

  tail <- c(
    "#'",
    "#' @return No return value.",
    sprintf("mod_patient_profile_params <- function(%s) NULL", paste(names(api), collapse = ", "))
  )

  mod_signature_path <- file.path(system.file("R", package = "dv.papo"), "mod_signature.R")

  writeLines(text = c(head, param_docs, tail), con = mod_signature_path)
}
